[versions]
activityCompose = "1.8.2"
agp = "8.2.1"
androidx-wearOngoing = "1.0.0"
coilCompose = "3.0.0-SNAPSHOT"
concurrentFuturesKtx = "1.1.0"
coreKtx = "1.12.0"
coreSplashscreen = "1.1.0-alpha02"
foundation = "1.6.0"
compose = "1.6.0"
compose-compiler = "1.5.7"
composeMaterial = "1.2.1"
composeFoundation = "1.2.1"
horologistComposeLayout = "0.5.19"
kotlin = "1.9.21"
kotlinxCollectionsImmutable = "0.3.7"
googleServices = "4.4.0"
kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.2"
ktor = "3.0.0-beta-1"
legacySupportV4 = "1.0.0"
lifecycleRuntimeKtx = "2.7.0"
material3 = "1.2.0-beta02"
percentlayout = "1.0.0"
playServicesLocation = "21.1.0"
playServicesWearable = "18.1.0"
protolayoutExpression = "1.1.0-beta01"
recyclerview = "1.3.2"
statelyConcurrency = "2.0.4"
tiles = "1.3.0-beta01"
uuid = "0.8.2"
wear = "1.3.0"
wearInput = "1.1.0"
wearOngoing = "1.1.0-alpha01"
wearPhoneInteractions = "1.0.1"
workRuntimeKtx = "2.9.0"
zoomable = "0.5.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "composeFoundation" }
androidx-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterial" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-window-size-clazz = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-percentlayout = { module = "androidx.percentlayout:percentlayout", version.ref = "percentlayout" }
androidx-protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "protolayoutExpression" }
androidx-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "protolayoutExpression" }
androidx-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "protolayoutExpression" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
androidx-wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }
androidx-wear-input-testing = { module = "androidx.wear:wear-input-testing", version.ref = "wearInput" }
androidx-wear-ongoing = { module = "androidx.wear:wear-ongoing", version.ref = "wearOngoing" }
androidx-wear-ongoing-v100 = { module = "androidx.wear:wear-ongoing", version.ref = "androidx-wearOngoing" }
androidx-wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "wearPhoneInteractions" }
androidx-wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "androidx-wearOngoing" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network = { module = "io.coil-kt.coil3:coil-network", version.ref = "coilCompose" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologistComposeLayout" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "statelyConcurrency" }
stately-concurrent-collections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "statelyConcurrency" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "zoomable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
