name: Mirror Privacy Policy
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  Mirror-Privacy-Policy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Privacy Policy
        run: |
          wget https://data.hkbuseta.com/PRIVACY_POLICY.html
      - name: Push to wear.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WEAR }}
        with:
          source-directory: './'
          target-directory: 'privacy-policy'
          destination-github-username: 'hkbus'
          destination-repository-name: 'wear.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
      - name: Push to watch.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WATCH }}
        with:
          source-directory: './'
          target-directory: 'privacy-policy'
          destination-github-username: 'hkbus'
          destination-repository-name: 'watch.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
