name: Build Desktop Windows
on:
  push:
  workflow_dispatch:

jobs:
  Build-Desktop-Windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: "17"
      - name: Build Desktop Windows
        shell: cmd
        run: |
          cd HKBusETA
          gradlew packageMsi
          cd ..
      - name: Grab File Name
        shell: pwsh
        run: |
          $directoryPath = "HKBusETA/composeApp/build/compose/binaries/main/msi"
          $fileName = Get-ChildItem -Path $directoryPath -Filter *.msi | Select-Object -ExpandProperty Name
          $version = $fileName
          "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Append
      - name: Distribution
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: HKBusETA/composeApp/build/compose/binaries/main/msi/${{ env.VERSION }}