name: Build Wasm
on:
  push:
  workflow_dispatch:

jobs:
  Build-Wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: "17"
      - name: Build Wasm
        run: |
          cd HKBusETA
          ./gradlew wasmJsBrowserDistribution
          cd ..
      - name: Distribution
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WEB }}
        with:
          source-directory: 'HKBusETA/composeApp/build/dist/wasmJs/productionExecutable'
          target-directory: 'web-app'
          destination-github-username: 'LOOHP'
          destination-repository-name: 'HK-Bus-ETA-AppLinks'
          user-email: jamesloohp@gmail.com
          target-branch: main
