name: Build Desktop Linux
on:
  push:
  workflow_dispatch:

jobs:
  Build-Desktop-Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: "17"
      - name: Build Desktop Linux
        run: |
          cd HKBusETA
          ./gradlew packageDeb
          cd ..
      - name: Grab File Name
        shell: bash
        run: |
          directoryPath="HKBusETA/composeApp/build/compose/binaries/main/deb"
          fileName=$(ls $directoryPath/*.deb | xargs -n 1 basename)
          echo "VERSION=$fileName" >> $GITHUB_ENV
      - name: Distribution
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: HKBusETA/composeApp/build/compose/binaries/main/deb/${{ env.VERSION }}