name: Data Fetching Processing
on:
  schedule:
    - cron: "45 21 * * *" # 05:45 (HKT) daily
  workflow_dispatch:

jobs:
  Fetch-Process-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: data-generation
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.11'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Fetching & Processing resources
        run: |
          python ./main.py
      - name: Update MD5
        run: md5sum data_full.json | cut -f1 -d ' ' | tr -d $'\n' > checksum.md5
      - name: Update Data Length
        run: |
          du -sb data.json | cut -f -1 > size.dat
          du -sb data_full.json | cut -f -1 > size_full.dat
      - name: GZip Data
        run: |
          gzip -k -f -9 data.json
          gzip -k -f -9 data_full.json
      - name: Update GZip Data Length
        run: |
          du -sb data.json.gz | cut -f -1 > size.gz.dat
          du -sb data_full.json.gz | cut -f -1 > size_full.gz.dat
      - name: Group resources to folder
        run: |
          mkdir data
          mv data.json data/
          mv data_formatted.json data/
          mv data_full.json data/
          mv data_full_formatted.json data/
          mv checksum.md5 data/
          mv size.dat data/
          mv data.json.gz data/
          mv size.gz.dat data/
          mv size_full.dat data/
          mv data_full.json.gz data/
          mv size_full.gz.dat data/
          mv last_updated.txt data/
      - name: Update resources
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: data
            commit-message: Update resources
            branch: data
            clean: false
      - name: Push to wear.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WEAR }}
        with:
          source-directory: 'data'
          target-directory: 'data'
          destination-github-username: 'hkbus'
          destination-repository-name: 'wear.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
      - name: Push to watch.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WATCH }}
        with:
          source-directory: 'data'
          target-directory: 'data'
          destination-github-username: 'hkbus'
          destination-repository-name: 'watch.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
