name: Mirror Pages
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  Mirror-Pages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: pages
      - name: Push to wear.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WEAR }}
        with:
          source-directory: ''
          target-directory: ''
          destination-github-username: 'hkbus'
          destination-repository-name: 'wear.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
      - name: Push to watch.hkbus.app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_WATCH }}
        with:
          source-directory: ''
          target-directory: ''
          destination-github-username: 'hkbus'
          destination-repository-name: 'watch.hkbus.app'
          user-email: jamesloohp@gmail.com
          target-branch: gh-pages
